import "@yourapp/styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import ThemeProvider from "../theme";
import { AuthProvider } from "../Auth/AuthProvider";
import { AuthGuard } from "../Auth/AuthGuard";
import localFont from "@next/font/local";
const segoeUI = localFont({
  src: "../public/font/Segoe fonts v1710/segoeui.ttf",
  preload: false,
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/instagram.ico" />
        <title>Insta clone</title>
      </Head>
      <ThemeProvider>
        <AuthProvider>
          {pageProps.requireAuth ? (
            <AuthGuard>
              <div className={segoeUI.className}>
                <Component {...pageProps} />
              </div>
            </AuthGuard>
          ) : (
            <div className={segoeUI.className}>
              <Component {...pageProps} />
            </div>
          )}
        </AuthProvider>
      </ThemeProvider>
    </>
  );
}
